version: '3'
services:
  drupal:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - mariadb
    environment:
      WWWUSER: '${WWWUSER}'
    container_name: 'drupal'
    volumes:
      - '.:/var/www/html/drupal'
    networks:
      - drupal
  mariadb:
    image: 'mysql:8.0.31'
    ports:
      - '33062:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'yousef'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'drupal'
      MYSQL_USER: 'yousef'
      MYSQL_PASSWORD: 'yousef'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mariadb:/var/lib/mysql'
    networks:
      - drupal
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-pyousef" ]
      retries: 3
      timeout: 5s

networks:
  drupal:
    driver: bridge
volumes:
  mariadb:
    driver: local
